FROM node:21-alpine

# Set the working directory
WORKDIR /app

# Increase memory limit to 2 GB
ENV NODE_OPTIONS="--max-old-space-size=3072"

# Copy all project files, including `tsconfig.json`
COPY . .

# Run the TypeScript and Vite builds
RUN npm run build
